services:
  mongodb:
    image: mongo:7.0
    container_name: ipl-management-sysdb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # database name that will be created automatically
      MONGO_INITDB_DATABASE: ipl_management
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local
